### ISSUE TITLE
Font Size of Task Instructions: When and how has this been controlled?

### ISSUE THREAD

**Issue by bradentompke** [UBC-VCL/VCLSHIVA#1]
**Experiment controls: long & short line asymmetry task, white stimuli on black background, all paper instructions in Times New Roman (TNR) font**

After contacting Emily Cramer, Alison Myers, and Frederic Ren, we now know exactly what font sizes they were using for the task instructions. It was necessary to contact them directly because this variable was not written in their reports. -->later contacted Kelly Wilkieson
Here are the details...

***Paper instructions have always been used for the visual search task.

Cramer: She called the visual search task instructions "SHIVA instructions." These instructions were always in font size **12** for the conditions she ran. Instructions for the object-liking and object-recognition tasks were on-screen.

Myers: Used paper instructions for all the tasks (visual search, object liking, object recognition). She always used font size **14** for her conditions.

Ren: He ran conditions with instructions on-screen and also conditions with off-screen instructions. Frederic always used font size **12** for the visual search task instructions, and font size **14** for the object liking and object recognition instructions for off-screen instruction conditions. Frederic thought he was using font size 14 for everything, but he wasn't.

Kelly: From her recollection, she used font size **12** for all the paper instructions.

**Comment by al2myers** [comment]
Hi Braden, just so you are aware, my section of the project was a
continuation from Kelly Wilkie and a cogs 402 student (Kayla something
...). You may also want I get in touch with them as they were the first to
use paper instructions.

Best,
Alison

**Comment by bradentompke** [comment]
Thanks Alison! That's great to know. We'll get in contact with them and probably update this issue.
